export const API_URL = 'http://localhost:5000/api';

export const BLOOD_GROUPS = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];
export const COMPONENTS = ['WHOLE_BLOOD', 'RBC', 'PLASMA', 'PLATELETS'];
export const ROLES = ['PATIENT', 'DONOR', 'HOSPITAL', 'BLOOD_BANK', 'ADMIN'];
export const URGENCY_LEVELS = ['NORMAL', 'URGENT', 'CRITICAL'];
export const REQUEST_STATUSES = [
  'PENDING', 'INVENTORY_SEARCH', 'BLOOD_RESERVED', 'DONOR_SEARCH', 
  'DONOR_ACCEPTED', 'DONATION_SCHEDULED', 'DONATION_COMPLETED', 
  'FULFILLED', 'CANCELLED', 'EXPIRED'
];
export const SEARCH_RADII = [5, 10, 20, 50];

export const STATUS_COLORS = {
  PENDING: '#6B7280', // gray
  INVENTORY_SEARCH: '#3B82F6', // blue
  BLOOD_RESERVED: '#10B981', // green
  DONOR_SEARCH: '#8B5CF6', // purple
  DONOR_ACCEPTED: '#10B981',
  DONATION_SCHEDULED: '#3B82F6',
  DONATION_COMPLETED: '#10B981',
  FULFILLED: '#10B981',
  CANCELLED: '#EF4444', // red
  EXPIRED: '#F59E0B' // yellow
};

export const URGENCY_COLORS = {
  NORMAL: '#10B981',
  URGENT: '#F59E0B',
  CRITICAL: '#EF4444'
};
